; Requires Inno Setup 7 or newer.
; Build with /DTargetArch=x64 or /DTargetArch=x86.

#ifndef TargetArch
  #error Define TargetArch as x64 or x86.
#endif
#if TargetArch == "x64"
  #define InstallerName "lever-installer-x64"
  #define BinaryPath "dist\x64\lever.exe"
#elif TargetArch == "x86"
  #define InstallerName "lever-installer-x86"
  #define BinaryPath "dist\x86\lever.exe"
#else
  #error TargetArch must be x64 or x86.
#endif

[Setup]
AppId=Lever Linux Tools
AppName=Lever Linux Tools
AppVersion=1.0.0
AppPublisher=Ethan Wang
SetupArchitecture={#TargetArch}
SetupIconFile=assets\lever.ico
OutputBaseFilename={#InstallerName}
OutputDir=.
Compression=lzma2/max
SolidCompression=yes

DefaultDirName={localappdata}\Programs\Lever
DefaultGroupName=Lever Linux Tools
PrivilegesRequired=lowest

#if TargetArch == "x64"
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
#else
ArchitecturesAllowed=x86compatible and not x64compatible
#endif
UninstallDisplayIcon={app}\lever.ico
ChangesEnvironment=yes

[Files]
Source: "assets\lever.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "THIRD_PARTY_NOTICES"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BinaryPath}"; DestDir: "{app}"; Flags: ignoreversion

[Run]
; PowerShell aliases take precedence over PATH wrappers, so install shell functions too.
Filename: "{app}\lever.exe"; Parameters: "install"; Flags: runhidden logoutput

[UninstallRun]
; Remove PowerShell profile functions and CMD integration while lever.exe still exists.
Filename: "{app}\lever.exe"; Parameters: "uninstall"; Flags: runhidden skipifdoesntexist; RunOnceId: "LeverShellCleanup"

; These files are generated by [Code], so register their cleanup explicitly.
[UninstallDelete]
Type: files; Name: "{app}\ls.bat"
Type: files; Name: "{app}\cat.bat"
Type: files; Name: "{app}\grep.bat"
Type: files; Name: "{app}\touch.bat"
Type: files; Name: "{app}\mkdir.bat"
Type: files; Name: "{app}\cp.bat"
Type: files; Name: "{app}\mv.bat"
Type: files; Name: "{app}\rm.bat"
Type: files; Name: "{app}\pwd.bat"
Type: files; Name: "{app}\clear.bat"
Type: files; Name: "{app}\nc.bat"
Type: files; Name: "{app}\du.bat"
Type: files; Name: "{app}\awk.bat"
Type: files; Name: "{app}\tail.bat"
Type: files; Name: "{app}\wc.bat"
Type: files; Name: "{app}\uname.bat"
Type: files; Name: "{app}\curl.bat"
Type: files; Name: "{app}\hash.bat"
Type: files; Name: "{app}\ping.bat"
Type: files; Name: "{app}\sed.bat"
Type: files; Name: "{app}\.lever-path-added"
Type: dirifempty; Name: "{app}"

[Code]

function NormalizePathEntry(Value: string): string;
begin
  Result := Trim(Value);
  if Length(Result) >= 2 then
  begin
    if (Result[1] = '"') and (Result[Length(Result)] = '"') then
      Result := Copy(Result, 2, Length(Result) - 2);
  end;
  while Length(Result) > 3 do
  begin
    if Result[Length(Result)] <> '\' then
      Break;
    Delete(Result, Length(Result), 1);
  end;
end;

// Split without DelimitedText: keep quotes, spaces and empty entries intact.
procedure SplitPath(const Value: string; Entries: TStringList);
var
  I, Start: Integer;
begin
  Entries.Clear;
  Start := 1;
  for I := 1 to Length(Value) do
  begin
    if Value[I] = ';' then
    begin
      Entries.Add(Copy(Value, Start, I - Start));
      Start := I + 1;
    end;
  end;
  Entries.Add(Copy(Value, Start, Length(Value) - Start + 1));
end;

function ReadUserPath(var Value: string): Boolean;
begin
  Value := '';
  if RegValueExists(HKCU, 'Environment', 'Path') then
    Result := RegQueryStringValue(HKCU, 'Environment', 'Path', Value)
  else
    Result := True;
end;

function WriteUserPath(const Value: string): Boolean;
begin
  // RegWriteStringValue retains REG_EXPAND_SZ for an existing expandable value.
  if RegValueExists(HKCU, 'Environment', 'Path') then
    Result := RegWriteStringValue(HKCU, 'Environment', 'Path', Value)
  else
    Result := RegWriteExpandStringValue(HKCU, 'Environment', 'Path', Value);
end;

procedure UpdateUserPath;
var
  OldPath, NewPath, AppPath, MarkerFile: string;
  Entries: TStringList;
  I: Integer;
  AlreadyExists, MarkerCreated: Boolean;
begin
  AppPath := ExpandConstant('{app}');
  MarkerFile := AppPath + '\.lever-path-added';
  if not ReadUserPath(OldPath) then
    RaiseException('Cannot read the current user PATH. It has not been modified.');

  Entries := TStringList.Create;
  try
    SplitPath(OldPath, Entries);
    AlreadyExists := False;
    // Remove existing Lever entries, preserving every other entry's order.
    for I := Entries.Count - 1 downto 0 do
    begin
      if CompareText(NormalizePathEntry(Entries[I]),
        NormalizePathEntry(AppPath)) = 0 then
      begin
        Entries.Delete(I);
        AlreadyExists := True;
      end;
    end;

    NewPath := AppPath;
    // An absent/empty PATH needs no separator; preserve other empty entries.
    if OldPath <> '' then
    begin
      for I := 0 to Entries.Count - 1 do
        NewPath := NewPath + ';' + Entries[I];
    end;
  finally
    Entries.Free;
  end;

  if NewPath = OldPath then
  begin
    Log('Lever is already first in the current user PATH.');
    Exit;
  end;

  // Moving a pre-existing entry does not make the installer its owner.
  // Keep any marker from an earlier installation in the same directory.
  MarkerCreated := False;
  if (not AlreadyExists) and (not FileExists(MarkerFile)) then
  begin
    if not SaveStringToFile(MarkerFile, '1' + #13#10, False) then
      RaiseException('Cannot save the PATH cleanup marker: ' + MarkerFile);
    MarkerCreated := True;
  end;
  if not WriteUserPath(NewPath) then
  begin
    if MarkerCreated then
      DeleteFile(MarkerFile);
    RaiseException('Cannot update the current user PATH.');
  end;
  Log('Placed Lever first in the current user PATH.');
end;

procedure RemoveUserPath;
var
  OldPath, NewPath, AppPath: string;
  Entries: TStringList;
  I: Integer;
  Removed: Boolean;
begin
  AppPath := ExpandConstant('{app}');
  if not FileExists(AppPath + '\.lever-path-added') then
    Exit;
  if not ReadUserPath(OldPath) then
  begin
    Log('Cannot read the current user PATH during uninstall.');
    SuppressibleMsgBox('Cannot read the current user PATH. Remove the Lever directory from PATH manually.',
      mbError, MB_OK, IDOK);
    Exit;
  end;

  Entries := TStringList.Create;
  try
    SplitPath(OldPath, Entries);
    Removed := False;
    for I := Entries.Count - 1 downto 0 do
    begin
      if CompareText(NormalizePathEntry(Entries[I]),
        NormalizePathEntry(AppPath)) = 0 then
      begin
        Entries.Delete(I);
        Removed := True;
      end;
    end;
    if not Removed then
      Exit;

    NewPath := '';
    for I := 0 to Entries.Count - 1 do
    begin
      if I > 0 then
        NewPath := NewPath + ';';
      NewPath := NewPath + Entries[I];
    end;
    if not WriteUserPath(NewPath) then
    begin
      Log('Cannot update the current user PATH during uninstall.');
      SuppressibleMsgBox('Cannot update the current user PATH. Remove the Lever directory from PATH manually.',
        mbError, MB_OK, IDOK);
    end;
  finally
    Entries.Free;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): string;
begin
  Result := '';
  if Pos(';', ExpandConstant('{app}')) > 0 then
    Result := 'The installation directory must not contain a semicolon (PATH separator).';
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  AppPath, BatFile, CmdName: string;
  BatContent: AnsiString;
  CmdList: array[0..19] of string;
  I: Integer;
begin
  if CurStep = ssPostInstall then
  begin
    AppPath := ExpandConstant('{app}');
    CmdList[0] := 'ls';    CmdList[1] := 'cat';   CmdList[2] := 'grep';  CmdList[3] := 'touch';
    CmdList[4] := 'mkdir'; CmdList[5] := 'cp';    CmdList[6] := 'mv';    CmdList[7] := 'rm';
    CmdList[8] := 'pwd';   CmdList[9] := 'clear'; CmdList[10] := 'nc';   CmdList[11] := 'du';
    CmdList[12] := 'awk';  CmdList[13] := 'tail'; CmdList[14] := 'wc';   CmdList[15] := 'uname';
    CmdList[16] := 'curl'; CmdList[17] := 'hash'; CmdList[18] := 'ping'; CmdList[19] := 'sed';

    for I := 0 to 19 do
    begin
      CmdName := CmdList[I];
      BatFile := AppPath + '\' + CmdName + '.bat';
      BatContent := '@echo off' + #13#10 +
        '"%~dp0lever.exe" ' + CmdName + ' %*' + #13#10 +
        'exit /b %errorlevel%' + #13#10;
      if not SaveStringToFile(BatFile, BatContent, False) then
        RaiseException('Cannot create command wrapper: ' + BatFile);
    end;
    UpdateUserPath;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  // Read the ownership marker before [UninstallDelete] removes it.
  if CurUninstallStep = usUninstall then
    RemoveUserPath;
end;
