package commands

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"unsafe"

	"golang.org/x/sys/windows"
	"golang.org/x/sys/windows/registry"

	"lever/engine"
	"lever/utils"
)

const (
	BlockStart = "# === Lever Linux Tools Autoload Start ==="
	BlockEnd   = "# === Lever Linux Tools Autoload End ==="
	shimMarker = "@rem Generated by Lever; do not edit"
	stateKey   = `Software\Lever`
	cmdKeyPath = `Software\Microsoft\Command Processor`
)

var commandNamePattern = regexp.MustCompile(`^[a-zA-Z0-9_-]+$`)

func NewInstallCmd(rootCmd *engine.Command) *engine.Command {
	return &engine.Command{
		Use:   "install",
		Short: "Install Lever commands in PowerShell and CMD",
		Args:  utils.NoArgs,
		RunE: func(c *engine.Command, args []string) error {
			exePath, err := os.Executable()
			if err != nil {
				return fmt.Errorf("installation failed: %w", err)
			}
			exePath, err = filepath.Abs(exePath)
			if err != nil {
				return fmt.Errorf("installation failed: %w", err)
			}

			var names []string
			for _, child := range rootCmd.Children {
				name := engine.CommandName(child.Use)
				if name != "install" && name != "uninstall" {
					names = append(names, name)
				}
			}

			psOK := installPowerShell(exePath, names)
			cmdErr := installCMD(exePath, names)
			if cmdErr != nil {
				fmt.Fprintf(os.Stderr, "CMD installation failed: %v\n", cmdErr)
			} else {
				fmt.Println("CMD commands installed. Reopen your terminal.")
			}
			if psOK {
				fmt.Println("PowerShell commands installed. Reopen your terminal.")
			}
			if !psOK && cmdErr != nil {
				return errors.New("PowerShell and CMD installation both failed")
			}
			return nil
		},
	}
}

func installPowerShell(exePath string, names []string) bool {
	quotedExe := "'" + strings.ReplaceAll(exePath, "'", "''") + "'"
	var lines []string
	for _, name := range names {
		lines = append(lines,
			fmt.Sprintf("if (Get-Alias %s -ErrorAction SilentlyContinue) { Remove-Item alias:%s }", name, name),
			fmt.Sprintf("function %s { if ($MyInvocation.ExpectingInput) { $input | & %s %s @args } else { & %s %s @args } }", name, quotedExe, name, quotedExe, name),
		)
	}
	block := "\n" + BlockStart + "\n" + strings.Join(lines, "\n") + "\n" + BlockEnd + "\n"
	success := false
	for _, path := range getProfilePaths() {
		if err := utils.EditProfileFile(path, true, func(existing string) (string, error) {
			return upsertProfileBlock(existing, block)
		}); err != nil {
			fmt.Fprintf(os.Stderr, "cannot write PowerShell profile %s: %v\n", path, err)
		} else {
			success = true
		}
	}
	return success
}

func installCMD(exePath string, names []string) error {
	shimDir, err := getShimDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(shimDir, 0755); err != nil {
		return err
	}
	for _, name := range names {
		if !commandNamePattern.MatchString(name) {
			return fmt.Errorf("invalid command name %q", name)
		}
		path := filepath.Join(shimDir, name+".cmd")
		if err := writeShim(path, exePath, name); err != nil {
			return err
		}
	}
	if err := addUserPath(shimDir); err != nil {
		return err
	}
	if err := clearLegacyAutoRun(exePath); err != nil {
		return err
	}
	return installCMDAutoRun(shimDir, exePath, names)
}

func cmdAutoRunValue(shimDir, exePath string, names []string, previous string) string {
	value := fmt.Sprintf(`set "PATH=%s;%%PATH%%"`, shimDir)
	for _, name := range names {
		value += fmt.Sprintf(` & doskey %s="%s" %s $*`, name, exePath, name)
	}
	if previous != "" {
		value += " & " + previous
	}
	return value
}

func installCMDAutoRun(shimDir, exePath string, names []string) error {
	key, _, err := registry.CreateKey(registry.CURRENT_USER, cmdKeyPath, registry.QUERY_VALUE|registry.SET_VALUE)
	if err != nil {
		return err
	}
	defer key.Close()
	current, kind, err := key.GetStringValue("AutoRun")
	present := err == nil
	if err != nil && !errors.Is(err, registry.ErrNotExist) {
		return err
	}
	state, _, err := registry.CreateKey(registry.CURRENT_USER, stateKey, registry.QUERY_VALUE|registry.SET_VALUE)
	if err != nil {
		return err
	}
	defer state.Close()
	installed, _, err := state.GetStringValue("InstalledAutoRun")
	if err == nil {
		if !present || current != installed {
			return errors.New("CMD AutoRun changed after Lever installation; refusing to overwrite it")
		}
		previous, _, err := state.GetStringValue("OriginalAutoRun")
		if err != nil {
			return err
		}
		desired := cmdAutoRunValue(shimDir, exePath, names, previous)
		if desired == current {
			return nil
		}
		if err := key.SetStringValue("AutoRun", desired); err != nil {
			return err
		}
		if err := state.SetStringValue("InstalledAutoRun", desired); err != nil {
			_ = key.SetStringValue("AutoRun", current)
			return err
		}
		return nil
	}
	if !errors.Is(err, registry.ErrNotExist) {
		return err
	}
	desired := cmdAutoRunValue(shimDir, exePath, names, current)
	if err := state.SetStringValue("OriginalAutoRun", current); err != nil {
		return err
	}
	if err := state.SetDWordValue("OriginalAutoRunKind", kind); err != nil {
		return err
	}
	if present {
		if err := state.SetDWordValue("OriginalAutoRunPresent", 1); err != nil {
			return err
		}
	} else if err := state.SetDWordValue("OriginalAutoRunPresent", 0); err != nil {
		return err
	}
	if err := state.SetStringValue("InstalledAutoRun", desired); err != nil {
		return err
	}
	if err := key.SetStringValue("AutoRun", desired); err != nil {
		_ = state.DeleteValue("InstalledAutoRun")
		return err
	}
	return nil
}

func removeCMDAutoRun() error {
	state, err := registry.OpenKey(registry.CURRENT_USER, stateKey, registry.QUERY_VALUE|registry.SET_VALUE)
	if errors.Is(err, registry.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	defer state.Close()
	installed, _, err := state.GetStringValue("InstalledAutoRun")
	if errors.Is(err, registry.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	key, err := registry.OpenKey(registry.CURRENT_USER, cmdKeyPath, registry.QUERY_VALUE|registry.SET_VALUE)
	if err != nil {
		return err
	}
	defer key.Close()
	current, _, err := key.GetStringValue("AutoRun")
	if err != nil || current != installed {
		return errors.New("CMD AutoRun changed after Lever installation; refusing to overwrite it")
	}
	previous, _, err := state.GetStringValue("OriginalAutoRun")
	if err != nil {
		return err
	}
	present, _, err := state.GetIntegerValue("OriginalAutoRunPresent")
	if err != nil {
		return err
	}
	kind, _, err := state.GetIntegerValue("OriginalAutoRunKind")
	if err != nil {
		return err
	}
	if present == 0 {
		err = key.DeleteValue("AutoRun")
	} else if kind == registry.EXPAND_SZ {
		err = key.SetExpandStringValue("AutoRun", previous)
	} else {
		err = key.SetStringValue("AutoRun", previous)
	}
	if err != nil {
		return err
	}
	if err := state.DeleteValue("InstalledAutoRun"); err != nil {
		return err
	}
	_ = state.DeleteValue("OriginalAutoRun")
	_ = state.DeleteValue("OriginalAutoRunPresent")
	_ = state.DeleteValue("OriginalAutoRunKind")
	return nil
}

func getShimDir() (string, error) {
	base := os.Getenv("LOCALAPPDATA")
	if base == "" {
		return "", errors.New("LOCALAPPDATA is not set")
	}
	return filepath.Join(base, "Lever", "bin"), nil
}

func shimContent(exePath, name string) string {
	// Escape percent signs in batch files while forwarding %* unchanged.
	escapedExe := strings.ReplaceAll(exePath, "%", "%%")
	return shimMarker + "\r\n@echo off\r\n@\"" + escapedExe + "\" " + name + " %*\r\n"
}

func writeShim(path, exePath, name string) error {
	old, err := os.ReadFile(path)
	if err == nil && !strings.HasPrefix(string(old), shimMarker+"\r\n") {
		return fmt.Errorf("refusing to overwrite existing file %s", path)
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.WriteFile(path, []byte(shimContent(exePath, name)), 0644)
}

func samePath(a, b string) bool {
	a = strings.Trim(strings.TrimSpace(a), "\"")
	b = strings.Trim(strings.TrimSpace(b), "\"")
	return strings.EqualFold(filepath.Clean(os.ExpandEnv(a)), filepath.Clean(os.ExpandEnv(b)))
}

func pathContains(list, dir string) bool {
	for _, part := range filepath.SplitList(list) {
		if part != "" && samePath(part, dir) {
			return true
		}
	}
	return false
}

func setPathValue(key registry.Key, value string, kind uint32) error {
	if kind == registry.EXPAND_SZ {
		return key.SetExpandStringValue("Path", value)
	}
	return key.SetStringValue("Path", value)
}

func addUserPath(dir string) error {
	key, err := registry.OpenKey(registry.CURRENT_USER, `Environment`, registry.QUERY_VALUE|registry.SET_VALUE)
	if err != nil {
		return err
	}
	defer key.Close()
	current, kind, err := key.GetStringValue("Path")
	if err != nil && !errors.Is(err, registry.ErrNotExist) {
		return err
	}
	if pathContains(current, dir) {
		return nil
	}
	next := strings.TrimRight(current, ";")
	if next != "" {
		next += ";"
	}
	next += dir
	if err := setPathValue(key, next, kind); err != nil {
		return err
	}
	state, _, err := registry.CreateKey(registry.CURRENT_USER, stateKey, registry.SET_VALUE)
	if err == nil {
		err = state.SetStringValue("AddedShimPath", dir)
		state.Close()
	}
	if err != nil {
		_ = setPathValue(key, current, kind)
		return err
	}
	notifyEnvironmentChange()
	return nil
}

func notifyEnvironmentChange() {
	name, err := windows.UTF16PtrFromString("Environment")
	if err != nil {
		return
	}
	var result uintptr
	proc := windows.NewLazySystemDLL("user32.dll").NewProc("SendMessageTimeoutW")
	_, _, _ = proc.Call(0xffff, 0x001a, 0, uintptr(unsafe.Pointer(name)), 0x0002, 1000, uintptr(unsafe.Pointer(&result)))
	runtime.KeepAlive(name)
}

func clearLegacyAutoRun(exePath string) error {
	key, err := registry.OpenKey(registry.CURRENT_USER, `Software\Microsoft\Command Processor`, registry.QUERY_VALUE|registry.SET_VALUE)
	if errors.Is(err, registry.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	defer key.Close()
	value, _, err := key.GetStringValue("AutoRun")
	if errors.Is(err, registry.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if isLegacyAutoRun(value, exePath) {
		return key.DeleteValue("AutoRun")
	}
	return nil
}

func isLegacyAutoRun(value, exePath string) bool {
	legacy := filepath.Join(filepath.Dir(exePath), "cmd_init.bat")
	if samePath(value, legacy) {
		return true
	}
	path := os.ExpandEnv(strings.Trim(value, "\""))
	if !filepath.IsAbs(path) || !strings.EqualFold(filepath.Base(path), "cmd_init.bat") {
		return false
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	lines := strings.Split(strings.ReplaceAll(string(content), "\r\n", "\n"), "\n")
	if len(lines) < 2 || lines[0] != "@echo off" {
		return false
	}
	seen := false
	for _, line := range lines[1:] {
		if line == "" {
			continue
		}
		if !strings.HasPrefix(line, "doskey ") || !strings.Contains(strings.ToLower(line), "lever.exe") || !strings.HasSuffix(line, " $*") {
			return false
		}
		seen = true
	}
	return seen
}

func NewUninstallCmd() *engine.Command {
	return &engine.Command{
		Use:   "uninstall",
		Short: "Remove Lever commands from PowerShell and CMD",
		Args:  utils.NoArgs,
		RunE: func(c *engine.Command, args []string) error {
			var failed bool
			for _, path := range getProfilePaths() {
				err := utils.EditProfileFile(path, false, func(existing string) (string, error) {
					return removeProfileBlock(existing)
				})
				if err != nil {
					fmt.Fprintf(os.Stderr, "cannot clean PowerShell profile %s: %v\n", path, err)
					failed = true
				}
			}
			if err := uninstallCMD(); err != nil {
				fmt.Fprintf(os.Stderr, "CMD cleanup failed: %v\n", err)
				failed = true
			}
			if exePath, err := os.Executable(); err == nil {
				if err := clearLegacyAutoRun(exePath); err != nil {
					fmt.Fprintf(os.Stderr, "legacy CMD configuration cleanup failed: %v\n", err)
					failed = true
				}
			}
			if !failed {
				fmt.Println("Lever command entries removed. Reopen your terminal.")
				return nil
			}
			return errors.New("some Lever command entries could not be removed")
		},
	}
}

func uninstallCMD() error {
	if err := removeCMDAutoRun(); err != nil {
		return err
	}
	dir, err := getShimDir()
	if err != nil {
		return err
	}
	if err := removeLeverShims(dir); err != nil {
		return err
	}
	state, err := registry.OpenKey(registry.CURRENT_USER, stateKey, registry.QUERY_VALUE|registry.SET_VALUE)
	if errors.Is(err, registry.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	defer state.Close()
	added, _, err := state.GetStringValue("AddedShimPath")
	if errors.Is(err, registry.ErrNotExist) || !samePath(added, dir) {
		return nil
	}
	if err != nil {
		return err
	}
	key, err := registry.OpenKey(registry.CURRENT_USER, `Environment`, registry.QUERY_VALUE|registry.SET_VALUE)
	if err != nil {
		return err
	}
	defer key.Close()
	current, kind, err := key.GetStringValue("Path")
	if err != nil {
		return err
	}
	var kept []string
	for _, part := range filepath.SplitList(current) {
		if part != "" && !samePath(part, dir) {
			kept = append(kept, part)
		}
	}
	if err := setPathValue(key, strings.Join(kept, ";"), kind); err != nil {
		return err
	}
	if err := state.DeleteValue("AddedShimPath"); err != nil {
		return err
	}
	notifyEnvironmentChange()
	return nil
}

func removeLeverShims(dir string) error {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.EqualFold(filepath.Ext(entry.Name()), ".cmd") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasPrefix(string(content), shimMarker+"\r\n") {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	if err := os.Remove(dir); err != nil {
		if errors.Is(err, windows.ERROR_DIR_NOT_EMPTY) || errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	if err := os.Remove(filepath.Dir(dir)); err != nil && !errors.Is(err, windows.ERROR_DIR_NOT_EMPTY) && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

func removeProfileBlock(existing string) (string, error) {
	start := strings.Index(existing, BlockStart)
	if start == -1 {
		return existing, nil
	}
	end := strings.Index(existing[start:], BlockEnd)
	if end == -1 {
		return "", errors.New("lever configuration block is missing its end marker")
	}
	return existing[:start] + existing[start+end+len(BlockEnd):], nil
}

func upsertProfileBlock(existing, block string) (string, error) {
	start := strings.Index(existing, BlockStart)
	if start == -1 {
		return existing + block, nil
	}
	end := strings.Index(existing[start:], BlockEnd)
	if end == -1 {
		return "", errors.New("lever configuration block is missing its end marker")
	}
	return existing[:start] + block + existing[start+end+len(BlockEnd):], nil
}

func getProfilePaths() []string {
	output, err := exec.Command("powershell.exe", "-NoProfile", "-NonInteractive", "-Command", "[Console]::OutputEncoding = [Text.Encoding]::UTF8; [Environment]::GetFolderPath('MyDocuments')").Output()
	if err != nil {
		return nil
	}
	documentsDir := strings.TrimSpace(string(output))
	if documentsDir == "" {
		return nil
	}
	return []string{
		filepath.Join(documentsDir, "WindowsPowerShell", "Microsoft.PowerShell_profile.ps1"),
		filepath.Join(documentsDir, "PowerShell", "Microsoft.PowerShell_profile.ps1"),
	}
}
